#!/bin/sh

if [ -z "$1" ] ; then
    echo "Usage: $0 [-d] devname"
    exit 1
fi

if [ "$1" == "-d" ] ; then
    remove_only=1
    shift
fi

if [ ! -b "$1" ] ; then
    echo "$1 is not a block device"
    exit 1
fi

dev=${1#/dev/}

if [ ! -d /sys/block/$dev ] ; then
    echo "$1 is not a disk device"
    exit 1
fi

blksize=$(/sbin/blockdev --getsize $1)
if [ $? -ne 0 ] ; then
    echo "blockdev --getsize $1 failed: $?"
    exit 1
fi

for link in $(udevinfo -q symlink -p /block/$dev) ; do
    case "$link" in
	*/by-id/ata*)
            atalink=${link#*/by-id/ata-}
	    ;;
	*/by-id/scsi*)
	    scsilink=${link#*/by-id/scsi-}
	    ;;
    esac
done
if [ "$scsilink" ] ; then
    serial="$scsilink"
    bus="scsi"
fi
if [ "$atalink" ] ; then
    serial="$atalink"
    bus="ata"
fi
if [ "$serial" ]; then
    # Remove existing rules
    echo "/$serial/d
w
q
" | ed /tmp/62-dm_linear.rules > /dev/null 2>&1
    [ "$remove_only" = 1 ] && exit 0
    # And create a new one
    cat >> /tmp/62-dm_linear.rules <<EOF
ACTION=="add", KERNEL=="sd*[!0-9]", ID_BUS=="$bus", ID_SERIAL=="$serial", RUN+="/lib/udev/dm_linear \$kernel $blksize $bus-$serial"
EOF
fi
